import React from "react";
import Head from "next/head";
import FullCalendar from "@fullcalendar/react";
import timeGridPlugin from "@fullcalendar/timegrid";
import interactionPlugin from "@fullcalendar/interaction";

const Home = () => {
  const handleClick = (a) => {
    return console.log(a.date);
  };
  return (
    <div className="h-screen w-full">
      <Head>
        <title>carry-reserve</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-14">
        <h1 className="text-4xl">carry-manager</h1>
      </header>
      <div className="h-[100px]">
        <FullCalendar
          plugins={[timeGridPlugin, interactionPlugin]}
          selectable={true}
          // weekends={false}
          headerToolbar={{
            left: "dayGridMonth,timeGridWeek,timeGridDay",
            center: "title",
            right: "prev,next",
          }}
          events={[
            { title: "event 1", date: "2021-11-04 6:00" },
            { title: "event 2", date: "2021-11-05" },
          ]}
          dateClick={handleClick}
        />
      </div>
    </div>
  );
};

export default Home;
