import React from "react";
import Head from "next/head";
import Calendar from "src/components/calendar";
import Header from "src/components/Header";
import List from "src/components/List";

const Home = () => {
  return (
    <div className="h-screen w-full">
      <Head>
        <title>carry-reserve</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="flex w-full h-[700px]">
        <Calendar />
      </div>
    </div>
  );
};

export default Home;
